name: app_rkode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter
  qr_flutter: ^4.0.0
  google_fonts: ^2.1.0
  eva_icons_flutter: ^3.0.2
  flutter_staggered_animations: ^1.0.0
  share_plus: ^3.0.4
  path_provider: ^2.0.8
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

